name: Build Typst document
on: [push, workflow_dispatch]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Typst
        uses: typst-community/setup-typst@v4.1.0
        with:
          typst-version: 0.13.1

      - name: Compile Notebook
        run: |
          typst compile main.typ --font-path=./assets/fonts/

      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: notebook
          path: main.pdf
